import { prisma } from "@/lib/prisma";

export default async function ProfitLossPage() {
  const accounts = await prisma.account.findMany({
    where: {
      type: {
        in: ["REVENUE", "EXPENSE"],
      },
    },
    orderBy: {
      code: "asc",
    },
  });

  const journalLines = await prisma.journalLine.findMany();

  const rows = accounts.map((account) => {
    const lines = journalLines.filter(
      (line) => line.accountId === account.id
    );

    const debit = lines
      .filter((line) => line.type === "DEBIT")
      .reduce((sum, line) => sum + Number(line.amount), 0);

    const credit = lines
      .filter((line) => line.type === "CREDIT")
      .reduce((sum, line) => sum + Number(line.amount), 0);

    let balance = 0;

    if (account.type === "REVENUE") {
      balance = credit - debit;
    } else {
      balance = debit - credit;
    }

    return {
      id: account.id,
      code: account.code,
      name: account.name,
      type: account.type,
      balance,
    };
  });

  const revenueRows = rows.filter(
    (row) => row.type === "REVENUE" && row.balance !== 0
  );

  const expenseRows = rows.filter(
    (row) => row.type === "EXPENSE" && row.balance !== 0
  );

  const totalRevenue = revenueRows.reduce(
    (sum, row) => sum + row.balance,
    0
  );

  const totalExpenses = expenseRows.reduce(
    (sum, row) => sum + row.balance,
    0
  );

  const netProfit = totalRevenue - totalExpenses;

  const formatCurrency = (value: number) =>
    `₹${value.toLocaleString("en-IN", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900">
          Profit & Loss
        </h1>

        <p className="mt-1 text-sm text-slate-500">
          Revenue, expenses and net profit based on recorded
          journal transactions.
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm font-medium text-slate-500">
            Total Revenue
          </p>

          <p className="mt-2 text-2xl font-bold text-slate-900">
            {formatCurrency(totalRevenue)}
          </p>
        </div>

        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm font-medium text-slate-500">
            Total Expenses
          </p>

          <p className="mt-2 text-2xl font-bold text-slate-900">
            {formatCurrency(totalExpenses)}
          </p>
        </div>

        <div
          className={`rounded-xl border p-6 shadow-sm ${
            netProfit >= 0
              ? "border-green-200 bg-green-50"
              : "border-red-200 bg-red-50"
          }`}
        >
          <p className="text-sm font-medium text-slate-600">
            {netProfit >= 0 ? "Net Profit" : "Net Loss"}
          </p>

          <p className="mt-2 text-2xl font-bold text-slate-900">
            {formatCurrency(Math.abs(netProfit))}
          </p>
        </div>
      </div>

      {/* Revenue */}
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-200 px-6 py-5">
          <h2 className="font-semibold text-slate-900">
            Revenue
          </h2>

          <p className="mt-1 text-xs text-slate-500">
            Income generated by the business
          </p>
        </div>

        {revenueRows.length === 0 ? (
          <div className="px-6 py-10 text-center text-sm text-slate-500">
            No revenue transactions recorded yet.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Code
                  </th>

                  <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Account
                  </th>

                  <th className="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Amount
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-slate-100">
                {revenueRows.map((row) => (
                  <tr key={row.id} className="hover:bg-slate-50">
                    <td className="px-6 py-4 font-mono text-sm font-semibold text-slate-900">
                      {row.code}
                    </td>

                    <td className="px-6 py-4 text-sm text-slate-700">
                      {row.name}
                    </td>

                    <td className="px-6 py-4 text-right text-sm font-medium text-slate-900">
                      {formatCurrency(row.balance)}
                    </td>
                  </tr>
                ))}
              </tbody>

              <tfoot className="border-t-2 border-slate-300 bg-slate-50">
                <tr>
                  <td
                    colSpan={2}
                    className="px-6 py-4 text-sm font-bold text-slate-900"
                  >
                    Total Revenue
                  </td>

                  <td className="px-6 py-4 text-right text-sm font-bold text-slate-900">
                    {formatCurrency(totalRevenue)}
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        )}
      </div>

      {/* Expenses */}
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-200 px-6 py-5">
          <h2 className="font-semibold text-slate-900">
            Expenses
          </h2>

          <p className="mt-1 text-xs text-slate-500">
            Costs incurred by the business
          </p>
        </div>

        {expenseRows.length === 0 ? (
          <div className="px-6 py-10 text-center text-sm text-slate-500">
            No expense transactions recorded yet.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Code
                  </th>

                  <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Account
                  </th>

                  <th className="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Amount
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-slate-100">
                {expenseRows.map((row) => (
                  <tr key={row.id} className="hover:bg-slate-50">
                    <td className="px-6 py-4 font-mono text-sm font-semibold text-slate-900">
                      {row.code}
                    </td>

                    <td className="px-6 py-4 text-sm text-slate-700">
                      {row.name}
                    </td>

                    <td className="px-6 py-4 text-right text-sm font-medium text-slate-900">
                      {formatCurrency(row.balance)}
                    </td>
                  </tr>
                ))}
              </tbody>

              <tfoot className="border-t-2 border-slate-300 bg-slate-50">
                <tr>
                  <td
                    colSpan={2}
                    className="px-6 py-4 text-sm font-bold text-slate-900"
                  >
                    Total Expenses
                  </td>

                  <td className="px-6 py-4 text-right text-sm font-bold text-slate-900">
                    {formatCurrency(totalExpenses)}
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        )}
      </div>

      {/* Net Result */}
      <div className="rounded-xl border-2 border-slate-900 bg-white p-6 shadow-sm">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-lg font-bold text-slate-900">
              {netProfit >= 0 ? "Net Profit" : "Net Loss"}
            </p>

            <p className="mt-1 text-sm text-slate-500">
              Revenue minus total expenses
            </p>
          </div>

          <p
            className={`text-2xl font-bold ${
              netProfit >= 0
                ? "text-green-700"
                : "text-red-700"
            }`}
          >
            {formatCurrency(Math.abs(netProfit))}
          </p>
        </div>
      </div>
    </div>
  );
}
